# Generated by Django 3.1.6 on 2021-02-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='task',
            field=models.ManyToManyField(blank=True, to='task_manager.Task'),
        ),
    ]
