# Generated by Django 3.1.6 on 2021-02-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20210212_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
